In [3]:
from spaco_py.SpaCoObject import SPACO
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from momentchi2 import wf, hbe

In [2]:
sf = np.load(
    "/home/krastegar0/SpaCo_py/src/spaco_py/sf_mat.npy", allow_pickle=False
)
neighbor = np.load(
    "/home/krastegar0/SpaCo_py/src/spaco_py/A_mat.npy", allow_pickle=False
)

In [3]:
#Loading the coorddinates 
coords = pd.read_excel('/home/krastegar0/SpaCo_py/src/spaco_py/coords_brain.xlsx')

In [4]:
def plot_spatial_heatmap(coords, values, title="Spatial Heatmap", cmap="viridis", point_size=50):
    """
    Plots a discrete heatmap based on coordinates and corresponding values.
    Args:
        coords (numpy.ndarray): Array of shape (n_samples, 2) containing x and y coordinates.
        values (numpy.ndarray): Array of shape (n_samples,) containing values corresponding to the coordinates.
        title (str): Title of the plot.
        cmap (str): Colormap to use for the heatmap.
        point_size (int): Size of the points in the scatter plot.
    """
    # Ensure inputs are NumPy arrays
    coords = np.array(coords)
    values = np.array(values)
    # Create the scatter plot
    plt.figure(figsize=(8, 6))
    scatter = plt.scatter(coords[:, 0], coords[:, 1], c=values, cmap=cmap, s=point_size, edgecolor="k")
    plt.colorbar(scatter, label="Values")
    plt.title(title)
    plt.xlabel("X Coordinate")
    plt.ylabel("Y Coordinate")
    plt.grid(True)
    plt.savefig(f'{title}.png', dpi=300, bbox_inches='tight')
    plt.show()
# Example usage
# Coordinates (x, y)
# coords = coords
# Values corresponding to the coordinates
# values = spac_patterns_X[:, 0]  # Use the first SpaCo pattern for demonstration
# Plot the heatmap
# plot_spatial_heatmap(coords, values, title="First SpaC",point_size=20)

In [5]:
testObj = SPACO(neighbormatrix=neighbor, sample_features=sf)

In [6]:
Pspac, Vkt =testObj.spaco_projection()

Inital CI: 1.765 - 1.767

INITIAL # of elements in CI: 0
 size of CI: 0.00153



## Remarks on Fig 1
The distribution of eigenvalues shows the non-random eigenvalues in blue and the random permuted eigenvalues in orange.
The non-random eigenvalues represent the true structure of the data, while the random permuted eigenvalues serve as a null distribution for comparison.
We use the upper 95% confidence interval of the random permuted eigenvalues to determine the significance of the non-random eigenvalues.
The non-random eigenvalues that exceed this threshold are considered significant and indicate the presence of meaningful patterns in the data.
The plot provides a visual representation of the eigenvalue distributions, allowing us to assess the significance of the non-random eigenvalues in relation to the random permuted eigenvalues.
      
      

## Determing a metric to see if this pattern is actually spatially 
Here we see our first spatial pattern but how can we tell if the patterns that we see are actually spatial or they are just artifacts. We look at the length of the projections as the measure of "Smoothness" for a spatial gene 

In [7]:
graphLaplacian=testObj._cache["spectral_results"][2]
graphLaplacian

array([[0.00037092, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00037092, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.00037092, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.00037092, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00037092,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00037092]], shape=(2696, 2696))

In [8]:
_, test_statistic = testObj.spaco_test(Pspac[:, 34])

pval: 0.3696040977826377
test statistic: 1.9464415030551285
lambda cut: 1.766962798370117


In [9]:
coeefficients = testObj._cache["sigma_eigh"]
coeefficients

array([0.00067831, 0.00068012, 0.00068166, 0.00068281, 0.00068566,
       0.00068679, 0.0006884 , 0.00069066, 0.00069113, 0.00069169,
       0.0006938 , 0.00069586, 0.00069644, 0.00070009, 0.00070053,
       0.00070276, 0.00070583, 0.00070833, 0.00071319, 0.00071373,
       0.00071412, 0.00071635, 0.00071874, 0.00072091, 0.00072325,
       0.000726  , 0.00073074, 0.00073162, 0.00073326, 0.00073476,
       0.00073712, 0.0007402 , 0.00074363, 0.00074548, 0.00074723])

In [10]:
pVal = 1-wf(coeefficients, x=test_statistic)
pVal            

np.float64(1.1102230246251565e-16)

In [11]:
sf

array([[-0.71401505, -0.34808321, -0.09112729, ...,  1.39672746,
        -0.95587448, -1.44889637],
       [-0.40716637, -0.55698328, -0.14597331, ..., -1.55168394,
        -3.03006255, -0.5522431 ],
       [-1.02430067, -0.49451424, -0.12965826, ..., -0.81094428,
         0.91945116, -0.27637594],
       ...,
       [ 0.12632418, -0.44350285, -0.1163142 , ...,  0.05668829,
        -0.1778188 , -0.56935161],
       [-0.8020468 , -0.38957994, -0.10213217, ...,  2.72528016,
         1.16362951, -1.61993973],
       [-0.78569242, -0.38187694, -0.10009644, ...,  1.87983883,
         1.17203493, -1.58871577]], shape=(2696, 3000))